(module
  
  (export "empty" (func 1))
  (export "singular" (func 2))
  (export "multi" (func 3))
  (export "nested" (func 4))
  (type $0 (func (param i32 i32) (result i32)))
  (type $2 (func (result i32)))
  (type $5 (func (result i32 i64 i32)))

  (func $0 (nop) )
  (func $1 (block end) (block end))
  (func $2 (type $2) (block (nop) end) (block (result i32) (i32.const 7) end))
  (func $3
    (type $2)
    (block (call 0) (call 0) (call 0) (call 0) end)
    (block (result i32) (call 0) (call 0) (call 0) (i32.const 7) (call 0) end)
    (drop)
    (block
      (type $5)
      (call 0)
      (call 0)
      (call 0)
      (i32.const 8)
      (call 0)
      (call 0)
      (call 0)
      (call 0)
      (i64.const 7)
      (call 0)
      (call 0)
      (call 0)
      (call 0)
      (i32.const 9)
      (call 0)
    end)
    (drop)
    (drop)
  )
  (func $4
    (type $2)
    (block
      (result i32)
      (block (call 0) (block end) (nop) end)
      (block (result i32) (call 0) (i32.const 9) end)
    end)
  )
)
